export const nodeTypeLabels: Record<string, string> = {
  start:       'Start',       end:        'End',
  agent:       'Agent',       http:       'HTTP Request',
  transform:   'Transform',   'if-else':  'If-Else',
  router:      'Router',      approval:   'Approval',
  mcp:         'MCP Tool',    memory:     'Memory',
  extract:     'Extract',     retriever:  'Retriever',
  guardrails:  'Guardrails',  code:       'Code',
  loop:        'Loop',        parallel:   'Parallel',
  wait:        'Wait',        variables:  'Variables',
  evaluator:   'Evaluator',   subworkflow:'Sub-workflow',
  slack:       'Slack',       github:     'GitHub',
  notion:      'Notion',      gmail:      'Gmail',
  filter:      'Filter',      merge:      'Merge',
  datetime:    'Date/Time',
  note:        'Note',
  frame:       'Frame',
};

export const nodeTypeColors: Record<string, string> = {
  start:       '#6366f1', end:        '#14b8a6',
  agent:       '#3b82f6', http:       '#8b5cf6',
  transform:   '#7c3aed', 'if-else':  '#f59e0b',
  router:      '#ea580c', approval:   '#f97316',
  mcp:         '#eab308', memory:     '#a855f7',
  extract:     '#0ea5e9', retriever:  '#10b981',
  guardrails:  '#ef4444', code:       '#64748b',
  loop:        '#0891b2', parallel:   '#6366f1',
  wait:        '#64748b', variables:  '#059669',
  evaluator:   '#d97706', subworkflow:'#7c3aed',
  slack:       '#4a154b', github:     '#1f2328',
  notion:      '#37352f', gmail:      '#ea4335',
  filter:      '#06b6d4', merge:      '#8b5cf6',
  datetime:    '#0d9488',
  note:        '#ca8a04', frame:      '#6366f1',
};
