import { CustomNode, NoteNode, StartNode, EndNode, FrameNode } from './custom-node';

export const nodeTypes = {
  start: StartNode,
  end: EndNode,
  agent: CustomNode,
  http: CustomNode,
  transform: CustomNode,
  'if-else': CustomNode,
  router: CustomNode,
  approval: CustomNode,
  mcp: CustomNode,
  memory: CustomNode,
  extract: CustomNode,
  retriever: CustomNode,
  guardrails: CustomNode,
  code: CustomNode,
  loop: CustomNode,
  parallel: CustomNode,
  wait: CustomNode,
  variables: CustomNode,
  evaluator: CustomNode,
  subworkflow: CustomNode,
  slack: CustomNode,
  github: CustomNode,
  notion: CustomNode,
  gmail: CustomNode,
  filter: CustomNode,
  merge: CustomNode,
  datetime: CustomNode,
  note: NoteNode,
  frame: FrameNode,
} as const;
