import type { ModelDefinition } from '../types';

export const OPENAI: ModelDefinition[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    description:
      'Flagship multimodal model. Excellent for vision tasks and general workflows.',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    tier: 'balanced',
    useCases: ['general', 'coding', 'vision', 'data-extraction'],
    capabilities: {
      vision: true,
      functionCalling: true,
      streaming: true,
      json: true,
    },
    costPer1mTokens: { input: 2.5, output: 10 },
    badge: 'recommended',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    description:
      'Ultra-affordable with vision. Best value for high-volume, simple tasks.',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    tier: 'fast',
    useCases: ['fast-response', 'data-extraction', 'conversation'],
    capabilities: {
      vision: true,
      functionCalling: true,
      streaming: true,
      json: true,
    },
    costPer1mTokens: { input: 0.15, output: 0.6 },
    badge: 'best-value',
  },
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    description: 'Optimized for long-context coding and instruction following.',
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    tier: 'balanced',
    useCases: ['coding', 'long-context', 'general'],
    capabilities: {
      vision: true,
      functionCalling: true,
      streaming: true,
      json: true,
    },
    costPer1mTokens: { input: 2, output: 8 },
  },
  {
    id: 'o4-mini',
    name: 'o4 Mini',
    provider: 'openai',
    description:
      'Fast reasoning model. Best for math, science, and multi-step logic.',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    tier: 'reasoning',
    useCases: ['reasoning', 'coding'],
    capabilities: { vision: true, functionCalling: true, streaming: true },
    costPer1mTokens: { input: 1.1, output: 4.4 },
    badge: 'best-reasoning',
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'openai',
    description:
      'Most powerful OpenAI reasoning model for frontier-level problems.',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    tier: 'reasoning',
    useCases: ['reasoning', 'coding'],
    capabilities: { vision: true, functionCalling: true, streaming: true },
    costPer1mTokens: { input: 10, output: 40 },
  },
];
